name: Bad CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: pip install -r app/requirements.txt

    - name: Build Docker image (slow)
      run: docker build --no-cache -f Dockerfile.bad -t fastapi-bad .

    - name: Simulate heavy task
      run: sleep 20